include: package:flutter_lints/flutter.yaml

linter:
  rules:
    {
      always_use_package_imports: true,
      avoid_dynamic_calls: true,
      no_logic_in_create_state: true,
      no_adjacent_strings_in_list: true,
      unnecessary_statements: true,
      always_declare_return_types: true,
      avoid_classes_with_only_static_members: true,
      avoid_positional_boolean_parameters: true,
      avoid_redundant_argument_values: true,
      avoid_return_types_on_setters: true,
      avoid_shadowing_type_parameters: true,
      cascade_invocations: true,
      join_return_with_assignment: true,
      prefer_conditional_assignment: true,
      require_trailing_commas: true,
      unnecessary_parenthesis: true,
      use_colored_box: true,
      use_decorated_box: true,
      use_setters_to_change_properties: true,
    }
